version: '3'
services:

  whalesfe:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: ./WhalesFrontEnd 

    # Mapping of container port to host
      
    ports:
      - "3000:8080"

    depends_on:
      - whalesapi

  whalesapi:
    build: ./WhalesAPI 
    
    ports:
      - "5000:80"

    depends_on:
      - whalesdb
    
  whalesdb:
    # image to fetch from docker hub
    image: mysql

    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
    